import { useCallback, useEffect, useState } from "react";


type Threat = {
  id: number;
  timestamp: string;
  source_ip: string;
  alert_type: string;
  severity: string;
  description: string;
};


type ThreatAnalysisData = {
  threat_score: number;
  total_threats: number;

  severity_counts: {
    CRITICAL: number;
    HIGH: number;
    MEDIUM: number;
    LOW: number;
  };

  latest_threats: Threat[];
};


export default function ThreatAnalysis() {

  const [data, setData] =
    useState<ThreatAnalysisData | null>(null);

  const [loading, setLoading] =
    useState(true);

  const [error, setError] =
    useState("");


  // -----------------------------------
  // Fetch Threat Analysis
  // -----------------------------------

  const fetchThreatAnalysis =
    useCallback(async () => {

      try {

        const response = await fetch(
          `${import.meta.env.VITE_API_URL}/threat-analysis`
        );


        if (!response.ok) {

          throw new Error(
            "Failed to fetch threat analysis"
          );

        }


        const result =
          await response.json();


        setData(result);

        setError("");

      }

      catch (err) {

        console.error(
          "Threat analysis error:",
          err
        );

        setError(
          "Unable to load threat analysis data."
        );

      }

      finally {

        setLoading(false);

      }

    }, []);


  // -----------------------------------
  // Initial Load + Live Updates
  // -----------------------------------

  useEffect(() => {

    fetchThreatAnalysis();


    function handleDashboardUpdate() {

      fetchThreatAnalysis();

    }


    window.addEventListener(
      "dashboard-update",
      handleDashboardUpdate
    );


    return () => {

      window.removeEventListener(
        "dashboard-update",
        handleDashboardUpdate
      );

    };

  }, [fetchThreatAnalysis]);


  // -----------------------------------
  // Severity Styling
  // -----------------------------------

  function getSeverityStyle(
    severity: string
  ) {

    switch (
      severity.toUpperCase()
    ) {

      case "CRITICAL":

        return (
          "bg-red-500/20 text-red-400"
        );


      case "HIGH":

        return (
          "bg-orange-500/20 text-orange-400"
        );


      case "MEDIUM":

        return (
          "bg-yellow-500/20 text-yellow-400"
        );


      default:

        return (
          "bg-green-500/20 text-green-400"
        );

    }

  }


  // -----------------------------------
  // Threat Score Styling
  // -----------------------------------

  function getThreatScoreStyle(
    score: number
  ) {

    if (score >= 75) {

      return "text-red-400";

    }


    if (score >= 50) {

      return "text-orange-400";

    }


    if (score >= 25) {

      return "text-yellow-400";

    }


    return "text-green-400";

  }


  // -----------------------------------
  // Loading
  // -----------------------------------

  if (loading) {

    return (

      <div className="flex h-96 items-center justify-center text-zinc-500">

        Loading threat intelligence...

      </div>

    );

  }


  // -----------------------------------
  // Error
  // -----------------------------------

  if (error || !data) {

    return (

      <div className="rounded-xl border border-red-900 bg-red-950/30 p-6 text-red-400">

        {error ||
          "Threat analysis data unavailable."}

      </div>

    );

  }


  return (

    <div className="space-y-6">


      {/* Header */}

      <div>

        <h1 className="text-4xl font-bold tracking-tight">

          Threat Analysis

        </h1>


        <p className="mt-2 text-zinc-500">

          Real-time security threat intelligence
          generated by the IDS.

        </p>

      </div>


      {/* Statistics */}

      <div className="grid grid-cols-1 gap-4 md:grid-cols-3">


        {/* Threat Score */}

        <div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-6">

          <p className="text-sm text-zinc-500">

            Overall Threat Score

          </p>


          <div className="mt-3 flex items-end gap-2">

            <p
              className={`
                text-5xl
                font-bold
                ${getThreatScoreStyle(
                  data.threat_score
                )}
              `}
            >

              {data.threat_score}

            </p>


            <span className="mb-1 text-zinc-500">

              / 100

            </span>

          </div>

        </div>


        {/* Total Threats */}

        <div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-6">

          <p className="text-sm text-zinc-500">

            Threats Analyzed

          </p>


          <p className="mt-3 text-5xl font-bold">

            {data.total_threats}

          </p>

        </div>


        {/* Critical Threats */}

        <div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-6">

          <p className="text-sm text-zinc-500">

            Critical Threats

          </p>


          <p className="mt-3 text-5xl font-bold text-red-400">

            {
              data.severity_counts
                .CRITICAL
            }

          </p>

        </div>

      </div>


      {/* Severity Breakdown */}

      <div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-6">


        <h2 className="text-lg font-semibold">

          Severity Breakdown

        </h2>


        <p className="mt-1 text-sm text-zinc-500">

          Distribution across the latest
          analyzed threats.

        </p>


        <div className="mt-6 grid grid-cols-2 gap-4 lg:grid-cols-4">


          <div className="rounded-xl border border-red-900/50 bg-red-950/20 p-5">

            <p className="text-sm text-red-400">

              Critical

            </p>

            <p className="mt-2 text-3xl font-bold">

              {
                data.severity_counts
                  .CRITICAL
              }

            </p>

          </div>


          <div className="rounded-xl border border-orange-900/50 bg-orange-950/20 p-5">

            <p className="text-sm text-orange-400">

              High

            </p>

            <p className="mt-2 text-3xl font-bold">

              {
                data.severity_counts
                  .HIGH
              }

            </p>

          </div>


          <div className="rounded-xl border border-yellow-900/50 bg-yellow-950/20 p-5">

            <p className="text-sm text-yellow-400">

              Medium

            </p>

            <p className="mt-2 text-3xl font-bold">

              {
                data.severity_counts
                  .MEDIUM
              }

            </p>

          </div>


          <div className="rounded-xl border border-green-900/50 bg-green-950/20 p-5">

            <p className="text-sm text-green-400">

              Low

            </p>

            <p className="mt-2 text-3xl font-bold">

              {
                data.severity_counts
                  .LOW
              }

            </p>

          </div>

        </div>

      </div>


      {/* Threat Table */}

      <div className="overflow-hidden rounded-2xl border border-zinc-800 bg-zinc-900">


        <div className="border-b border-zinc-800 px-6 py-5">

          <h2 className="text-lg font-semibold">

            Detected Threats

          </h2>


          <p className="text-sm text-zinc-500">

            Latest security events detected
            by the IDS.

          </p>

        </div>


        <div className="max-h-[550px] overflow-auto">


          <table className="w-full text-left text-sm">


            <thead className="sticky top-0 bg-zinc-950 text-zinc-500">

              <tr>

                <th className="px-5 py-4">
                  Time
                </th>

                <th className="px-5 py-4">
                  Attack
                </th>

                <th className="px-5 py-4">
                  Source IP
                </th>

                <th className="px-5 py-4">
                  Severity
                </th>

                <th className="px-5 py-4">
                  Evidence
                </th>

              </tr>

            </thead>


            <tbody>

              {data.latest_threats.map(
                (threat) => (

                  <tr
                    key={threat.id}
                    className="border-t border-zinc-800/70 hover:bg-zinc-800/50"
                  >


                    <td className="whitespace-nowrap px-5 py-4 text-zinc-400">

                      {new Date(
                        threat.timestamp
                      ).toLocaleTimeString()}

                    </td>


                    <td className="px-5 py-4 font-medium">

                      {threat.alert_type}

                    </td>


                    <td className="px-5 py-4 font-mono text-xs">

                      {threat.source_ip}

                    </td>


                    <td className="px-5 py-4">

                      <span
                        className={`
                          rounded-full
                          px-2.5
                          py-1
                          text-xs
                          font-medium
                          ${getSeverityStyle(
                            threat.severity
                          )}
                        `}
                      >

                        {threat.severity}

                      </span>

                    </td>


                    <td className="max-w-md px-5 py-4 text-zinc-400">

                      {threat.description}

                    </td>


                  </tr>

                )
              )}

            </tbody>

          </table>

        </div>

      </div>

    </div>

  );

}